//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotCommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int Id { get; set; }
        public int ProductVariantId { get; set; }
        public Nullable<int> PersonId { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual ProductVariant ProductVariant { get; set; }
    }
}
